services:
  frontend:
    env_file: .env
    restart: on-failure
    build: ./
    hostname: splitoshi
    ports:
      - "3000:3000"
    network_mode: host
  db:
    restart: always
    image: postgres:latest
    volumes:
      - ../database:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=postgres